version: "3.4"

services:
  provision:
    image: djmittens/dployr
    build: ./
    network_mode: host
    volumes:
      - ${SSH_FOLDER:-~/.ssh}:/root/.ssh
    environment:
      - TARGET_HOST=${TARGET_HOST:-localhost}
